### ISSUE TITLE
Noob friendly docs please c:

### ISSUE THREAD

**Issue by ChillerDragon** [Ryozuki/teelib#1]
We already have some teeworlds libs like:

https://github.com/erdbeere/tml

https://github.com/heinrich5991/libtw2

But for me they are all pretty useless because i am a complete nobo.
Please add some nice easy to use examples and this lib could give a big value for many people out there.

**Comment by edg-l** [comment]
I'll do that when i finish it

**Comment by ChillerDragon** [comment]
@Ryozuki sounds like never to me ._.
But i hope you proof me wrong <3

**Comment by ChillerDragon** [comment]
:cry:
